if(NOT SET_UP_CONFIGURATIONS_DONE)
	set(SET_UP_CONFIGURATIONS_DONE TRUE)
	get_property(isMultiConfig GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
	
	if(isMultiConfig)
		set(CMAKE_CONFIGURATION_TYPES "Debug;Release;Profile" CACHE STRING "" FORCE) 
	else()
		if(NOT CMAKE_BUILD_TYPE)
			message("Defaulting to release build.")
			set(CMAKE_BUILD_TYPE Release CACHE STRING "" FORCE)
		endif()

		set_property(CACHE CMAKE_BUILD_TYPE PROPERTY HELPSTRING "Choose the type of build")
		set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug;Release;Profile")
	endif()

	#set(CMAKE_C_FLAGS_PROFILE "...")
	#set(CMAKE_CXX_FLAGS_PROFILE "...")
	#set(CMAKE_EXE_LINKER_FLAGS_PROFILE "...")
	string(APPEND CMAKE_CXX_FLAGS_RELEASE " -O3 -DNDEBUG")
	string(APPEND CMAKE_CXX_FLAGS_DEBUG " -Wall -Werror -Wextra -fexceptions -O0 -g3 -ggdb -DDEBUG")
	string(APPEND CMAKE_C_FLAGS_RELEASE " -O3 -DNDEBUG")
	string(APPEND CMAKE_C_FLAGS_DEBUG " -Wall -Werror -Wextra -fexceptions -O0 -g3 -ggdb -DDEBUG")
endif()
